[package]
name = "radcam-manager"
version = "0.2.0-beta.1"
edition = "2024"
license = "MIT"
default-run = "radcam-manager"

[dependencies]
autopilot = { path="../libs/autopilot" }
mcm_client = { path="../libs/mcm_client" }
radcam_manager = { path="../libs/radcam_manager" }
settings = { path="../libs/settings" }
web_client = { path="../libs/web_client" }

anyhow = "1.0.98"
chrono = { version = "0.4.40", default-features = false }
clap = { version = "4.5.26", features = ["derive"] }
once_cell = "1.21.3"
shellexpand = "3.1.1"
tokio = { version = "1.44.2", features = ["full"] }
tracing = { version = "0.1.41", features = ["log", "async-await"] }

[build-dependencies]
vergen-gix = { version = "1.0.9", default-features = false, features = ["build", "cargo"] }